<?php
/**
 * Auto generated from WeChat.proto at 2019-11-11 02:28:27
 */

namespace {
/**
 * CGI_TYPE enum
 */
final class CGI_TYPE
{
    const CGI_TYPE_DEFAULT = 0;
    const CGI_TYPE_SEARCHCONTACT = 106;
    const CGI_TYPE_GETMSGIMG = 109;
    const CGI_TYPE_CREATECHATROOM = 119;
    const CGI_TYPE_ADDCHATROOMMEMBER = 120;
    const CGI_TYPE_BATCHGETHEADIMG = 123;
    const CGI_TYPE_UPLOADVOICE = 127;
    const CGI_TYPE_DOWNLOADVOICE = 128;
    const CGI_TYPE_UPLOADMCONTACT = 133;
    const CGI_TYPE_NEWGETINVITEFRIEND = 135;
    const CGI_TYPE_VERIFYUSER = 137;
    const CGI_TYPE_NEWSYNC = 138;
    const CGI_TYPE_LBSFIND = 148;
    const CGI_TYPE_UPLOADVIDEO = 149;
    const CGI_TYPE_GETQRCODE = 168;
    const CGI_TYPE_SENDEMOJI = 175;
    const CGI_TYPE_DELCHATROOMMEMBER = 179;
    const CGI_TYPE_GETCONTACT = 182;
    const CGI_TYPE_MASSSEND = 193;
    const CGI_TYPE_MMSNSUPLOAD = 207;
    const CGI_TYPE_MMSNSPORT = 209;
    const CGI_TYPE_MMSNSOBJECTDETAIL = 210;
    const CGI_TYPE_MMSNSTIMELINE = 211;
    const CGI_TYPE_MMSNSUSERPAGE = 212;
    const CGI_TYPE_MMSNSCOMMENT = 213;
    const CGI_TYPE_MMSNSSYNC = 214;
    const CGI_TYPE_SNSOBJECTOP = 218;
    const CGI_TYPE_SENDAPPMSG = 222;
    const CGI_TYPE_GETCHATROOMINFODETAIL = 223;
    const CGI_TYPE_GETA8KEY = 233;
    const CGI_TYPE_STATUSNOTIFY = 251;
    const CGI_TYPE_MMSNSTAGLIST = 292;
    const CGI_TYPE_GETPROFILE = 302;
    const CGI_TYPE_GETCDNDNS = 379;
    const CGI_TYPE_TENPAY = 385;
    const CGI_TYPE_FAVSYNC = 400;
    const CGI_TYPE_ADDFAVITEM = 401;
    const CGI_TYPE_BATCHGETFAVITEM = 402;
    const CGI_TYPE_GETFAVINFO = 438;
    const CGI_TYPE_GETOPENIMRESOURCE = 453;
    const CGI_TYPE_TIMESEED = 477;
    const CGI_TYPE_GETPAYFUNCTIONLIST = 495;
    const CGI_TYPE_GETLOGINQRCODE = 502;
    const CGI_TYPE_CHECKLOGINQRCODE = 503;
    const CGI_TYPE_HEARTBEAT = 518;
    const CGI_TYPE_GETEMOTIONDESC = 521;
    const CGI_TYPE_NEWSENDMSG = 522;
    const CGI_TYPE_GETONLINEINFO = 526;
    const CGI_TYPE_GETCHATROOMMEMBERDETAIL = 551;
    const CGI_TYPE_UPLOADIMAGE = 625;
    const CGI_TYPE_GETCONTACTLABELLIST = 639;
    const CGI_TYPE_PUSHLOGINURL = 654;
    const CGI_TYPE_OPLOG = 681;
    const CGI_TYPE_MANUALAUTH = 701;
    const CGI_TYPE_INITCONTACT = 851;
    const CGI_TYPE_EXTDEVICELOGINCONFIRMGET = 971;
    const CGI_TYPE_SETCHATROOMANNOUNCEMENT = 993;
    const CGI_TYPE_ADEXPOSURE = 1231;
    const CGI_TYPE_ADCLICK = 1232;
    const CGI_TYPE_BINDQUERYNEW = 1501;
    const CGI_TYPE_QRYLISTWXHB = 1514;
    const CGI_TYPE_RECEIVEWXHB = 1581;
    const CGI_TYPE_QRYDETAILWXHB = 1585;
    const CGI_TYPE_F2FQRCODE = 1588;
    const CGI_TYPE_TRANSFERSETF2FFEE = 1623;
    const CGI_TYPE_TRANSFERQUERY = 1628;
    const CGI_TYPE_GETBANNERINFO = 1679;
    const CGI_TYPE_WISHWXHB = 1682;
    const CGI_TYPE_OPENWXHB = 1685;
    const CGI_TYPE_TRANSFEROPERATION = 1691;
    const CGI_TYPE_GETTRANSFERWORDINH = 1992;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'CGI_TYPE_DEFAULT' => self::CGI_TYPE_DEFAULT,
            'CGI_TYPE_SEARCHCONTACT' => self::CGI_TYPE_SEARCHCONTACT,
            'CGI_TYPE_GETMSGIMG' => self::CGI_TYPE_GETMSGIMG,
            'CGI_TYPE_CREATECHATROOM' => self::CGI_TYPE_CREATECHATROOM,
            'CGI_TYPE_ADDCHATROOMMEMBER' => self::CGI_TYPE_ADDCHATROOMMEMBER,
            'CGI_TYPE_BATCHGETHEADIMG' => self::CGI_TYPE_BATCHGETHEADIMG,
            'CGI_TYPE_UPLOADVOICE' => self::CGI_TYPE_UPLOADVOICE,
            'CGI_TYPE_DOWNLOADVOICE' => self::CGI_TYPE_DOWNLOADVOICE,
            'CGI_TYPE_UPLOADMCONTACT' => self::CGI_TYPE_UPLOADMCONTACT,
            'CGI_TYPE_NEWGETINVITEFRIEND' => self::CGI_TYPE_NEWGETINVITEFRIEND,
            'CGI_TYPE_VERIFYUSER' => self::CGI_TYPE_VERIFYUSER,
            'CGI_TYPE_NEWSYNC' => self::CGI_TYPE_NEWSYNC,
            'CGI_TYPE_LBSFIND' => self::CGI_TYPE_LBSFIND,
            'CGI_TYPE_UPLOADVIDEO' => self::CGI_TYPE_UPLOADVIDEO,
            'CGI_TYPE_GETQRCODE' => self::CGI_TYPE_GETQRCODE,
            'CGI_TYPE_SENDEMOJI' => self::CGI_TYPE_SENDEMOJI,
            'CGI_TYPE_DELCHATROOMMEMBER' => self::CGI_TYPE_DELCHATROOMMEMBER,
            'CGI_TYPE_GETCONTACT' => self::CGI_TYPE_GETCONTACT,
            'CGI_TYPE_MASSSEND' => self::CGI_TYPE_MASSSEND,
            'CGI_TYPE_MMSNSUPLOAD' => self::CGI_TYPE_MMSNSUPLOAD,
            'CGI_TYPE_MMSNSPORT' => self::CGI_TYPE_MMSNSPORT,
            'CGI_TYPE_MMSNSOBJECTDETAIL' => self::CGI_TYPE_MMSNSOBJECTDETAIL,
            'CGI_TYPE_MMSNSTIMELINE' => self::CGI_TYPE_MMSNSTIMELINE,
            'CGI_TYPE_MMSNSUSERPAGE' => self::CGI_TYPE_MMSNSUSERPAGE,
            'CGI_TYPE_MMSNSCOMMENT' => self::CGI_TYPE_MMSNSCOMMENT,
            'CGI_TYPE_MMSNSSYNC' => self::CGI_TYPE_MMSNSSYNC,
            'CGI_TYPE_SNSOBJECTOP' => self::CGI_TYPE_SNSOBJECTOP,
            'CGI_TYPE_SENDAPPMSG' => self::CGI_TYPE_SENDAPPMSG,
            'CGI_TYPE_GETCHATROOMINFODETAIL' => self::CGI_TYPE_GETCHATROOMINFODETAIL,
            'CGI_TYPE_GETA8KEY' => self::CGI_TYPE_GETA8KEY,
            'CGI_TYPE_STATUSNOTIFY' => self::CGI_TYPE_STATUSNOTIFY,
            'CGI_TYPE_MMSNSTAGLIST' => self::CGI_TYPE_MMSNSTAGLIST,
            'CGI_TYPE_GETPROFILE' => self::CGI_TYPE_GETPROFILE,
            'CGI_TYPE_GETCDNDNS' => self::CGI_TYPE_GETCDNDNS,
            'CGI_TYPE_TENPAY' => self::CGI_TYPE_TENPAY,
            'CGI_TYPE_FAVSYNC' => self::CGI_TYPE_FAVSYNC,
            'CGI_TYPE_ADDFAVITEM' => self::CGI_TYPE_ADDFAVITEM,
            'CGI_TYPE_BATCHGETFAVITEM' => self::CGI_TYPE_BATCHGETFAVITEM,
            'CGI_TYPE_GETFAVINFO' => self::CGI_TYPE_GETFAVINFO,
            'CGI_TYPE_GETOPENIMRESOURCE' => self::CGI_TYPE_GETOPENIMRESOURCE,
            'CGI_TYPE_TIMESEED' => self::CGI_TYPE_TIMESEED,
            'CGI_TYPE_GETPAYFUNCTIONLIST' => self::CGI_TYPE_GETPAYFUNCTIONLIST,
            'CGI_TYPE_GETLOGINQRCODE' => self::CGI_TYPE_GETLOGINQRCODE,
            'CGI_TYPE_CHECKLOGINQRCODE' => self::CGI_TYPE_CHECKLOGINQRCODE,
            'CGI_TYPE_HEARTBEAT' => self::CGI_TYPE_HEARTBEAT,
            'CGI_TYPE_GETEMOTIONDESC' => self::CGI_TYPE_GETEMOTIONDESC,
            'CGI_TYPE_NEWSENDMSG' => self::CGI_TYPE_NEWSENDMSG,
            'CGI_TYPE_GETONLINEINFO' => self::CGI_TYPE_GETONLINEINFO,
            'CGI_TYPE_GETCHATROOMMEMBERDETAIL' => self::CGI_TYPE_GETCHATROOMMEMBERDETAIL,
            'CGI_TYPE_UPLOADIMAGE' => self::CGI_TYPE_UPLOADIMAGE,
            'CGI_TYPE_GETCONTACTLABELLIST' => self::CGI_TYPE_GETCONTACTLABELLIST,
            'CGI_TYPE_PUSHLOGINURL' => self::CGI_TYPE_PUSHLOGINURL,
            'CGI_TYPE_OPLOG' => self::CGI_TYPE_OPLOG,
            'CGI_TYPE_MANUALAUTH' => self::CGI_TYPE_MANUALAUTH,
            'CGI_TYPE_INITCONTACT' => self::CGI_TYPE_INITCONTACT,
            'CGI_TYPE_EXTDEVICELOGINCONFIRMGET' => self::CGI_TYPE_EXTDEVICELOGINCONFIRMGET,
            'CGI_TYPE_SETCHATROOMANNOUNCEMENT' => self::CGI_TYPE_SETCHATROOMANNOUNCEMENT,
            'CGI_TYPE_ADEXPOSURE' => self::CGI_TYPE_ADEXPOSURE,
            'CGI_TYPE_ADCLICK' => self::CGI_TYPE_ADCLICK,
            'CGI_TYPE_BINDQUERYNEW' => self::CGI_TYPE_BINDQUERYNEW,
            'CGI_TYPE_QRYLISTWXHB' => self::CGI_TYPE_QRYLISTWXHB,
            'CGI_TYPE_RECEIVEWXHB' => self::CGI_TYPE_RECEIVEWXHB,
            'CGI_TYPE_QRYDETAILWXHB' => self::CGI_TYPE_QRYDETAILWXHB,
            'CGI_TYPE_F2FQRCODE' => self::CGI_TYPE_F2FQRCODE,
            'CGI_TYPE_TRANSFERSETF2FFEE' => self::CGI_TYPE_TRANSFERSETF2FFEE,
            'CGI_TYPE_TRANSFERQUERY' => self::CGI_TYPE_TRANSFERQUERY,
            'CGI_TYPE_GETBANNERINFO' => self::CGI_TYPE_GETBANNERINFO,
            'CGI_TYPE_WISHWXHB' => self::CGI_TYPE_WISHWXHB,
            'CGI_TYPE_OPENWXHB' => self::CGI_TYPE_OPENWXHB,
            'CGI_TYPE_TRANSFEROPERATION' => self::CGI_TYPE_TRANSFEROPERATION,
            'CGI_TYPE_GETTRANSFERWORDINH' => self::CGI_TYPE_GETTRANSFERWORDINH,
        );
    }
}
}