<?php
/**
 * Auto generated from WeChat.proto at 2019-11-11 02:28:27
 */

namespace {
/**
 * enMMTenPayCgiCmd enum
 */
final class enMMTenPayCgiCmd
{
    const MMTENPAY_CGICMD_AUTHEN = 0;
    const MMTENPAY_CGICMD_VERIFY = 1;
    const MMTENPAY_CGICMD_USER_ROLL = 3;
    const MMTENPAY_CGICMD_USER_ROLL_BATCH = 4;
    const MMTENPAY_CGICMD_QRCODE_CREATE = 5;
    const MMTENPAY_CGICMD_QRCODE_USE = 6;
    const MMTENPAY_CGICMD_BANK_QUERY = 7;
    const MMTENPAY_CGICMD_CHANGE_PWD = 9;
    const MMTENPAY_CGICMD_RESET_PWD_AUTHEN = 10;
    const MMTENPAY_CGICMD_RESET_PWD_VERIFY = 11;
    const MMTENPAY_CGICMD_BIND_AUTHEN = 12;
    const MMTENPAY_CGICMD_BIND_VERIFY = 13;
    const MMTENPAY_CGICMD_UNBIND = 14;
    const MMTENPAY_CGICMD_BANKCARDBIN_QUERY = 15;
    const MMTENPAY_CGICMD_VERIFY_REG = 16;
    const MMTENPAY_CGICMD_BIND_VERIFY_REG = 17;
    const MMTENPAY_CGICMD_CHECK_PWD = 18;
    const MMTENPAY_CGICMD_TIMESEED = 19;
    const MMTENPAY_CGICMD_RESET_PWD = 20;
    const MMTENPAY_CGICMD_PUBLIC_API = 21;
    const MMTENPAY_BIZ_CGICMD_WEB_QUERY_CHECK_RECORD = 22;
    const MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_CHECK_RECORD = 23;
    const MMTENPAY_BIZ_CGICMD_WEB_QUERY_CHECK_RESULT = 24;
    const MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_CHECK_RESULT = 25;
    const MMTENPAY_BIZ_CGICMD_WEB_NOTIFY_CHECK_RESULT = 26;
    const MMTENPAY_BIZ_CGICMD_PLATFORM_NOTIFY_CHECK_RESULT = 27;
    const MMTENPAY_CGICMD_MCH_TRADE = 28;
    const MMTENPAY_GW_CGICMD_NORMAL_ORDER_QUERY = 29;
    const MMTENPAY_CGICMD_QUERY_USER_TYPE = 30;
    const MMTENPAY_GW_CGICMD_VERIFY_NOTIFY_ID = 31;
    const MMTENPAY_GW_CGICMD_NORMAL_REFUND_QUERY = 33;
    const MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_BZJ_INFO = 34;
    const MMTENPAY_CGICMD_WX_OFFLINE_AUTHEN = 35;
    const MMTENPAY_CGICMD_WX_OFFLINE_PAY = 36;
    const MMTENPAY_CGICMD_IMPORT_BIND_QUERY = 37;
    const MMTENPAY_CGICMD_IMPORT_ENCRYPT_QUERY = 38;
    const MMTENPAY_CGICMD_WX_FUND_BUY = 39;
    const MMTENPAY_CGICMD_WX_FUND_REDEM = 40;
    const MMTENPAY_CGICMD_WX_FUND_CHANGE = 41;
    const MMTENPAY_CGICMD_WX_FUND_BINDSP_QUERY = 42;
    const MMTENPAY_CGICMD_WX_FUND_ACCOUNT_QUERY = 43;
    const MMTENPAY_CGICMD_WX_FUND_PROFIT_QUERY = 44;
    const MMTENPAY_CGICMD_WX_FUND_SUPPORT_BANK = 45;
    const MMTENPAY_CGICMD_OFFLINE_CREATE = 46;
    const MMTENPAY_CGICMD_OFFLINE_CLOSE = 47;
    const MMTENPAY_CGICMD_OFFLINE_FPAY = 48;
    const MMTENPAY_CGICMD_OFFLINE_QUERY_USER = 49;
    const MMTENPAY_CGICMD_OFFLINE_CHG_FEE = 50;
    const MMTENPAY_CGICMD_OFFLINE_UNFREEZE = 51;
    const MMTENPAY_CGICMD_OFFLINE_GET_TOKEN = 52;
    const MMTENPAY_CGICMD_WX_HB_REDPACKETNOTIFY = 53;
    const MMTENPAY_CGICMD_WX_SP_CLOSE_ORDER = 54;
    const MMTENPAY_BIZ_CGICMD_QUERY_NEW_PARTNER_ID = 55;
    const MMTENPAY_BIZ_CGICMD_QUERY_BIZ_CHECK_RESULT = 56;
    const MMTENPAY_CGICMD_WXCREDIT_QUERY = 57;
    const MMTENPAY_CGICMD_WXCREDIT_QUERY_CARD_DETAIL = 58;
    const MMTENPAY_CGICMD_WXCREDIT_QUERY_QUESTION = 59;
    const MMTENPAY_CGICMD_WXCREDIT_COMMIT_QUESTION = 60;
    const MMTENPAY_CGICMD_WXCREDIT_REPAY = 61;
    const MMTENPAY_CGICMD_WXCREDIT_UNBIND = 62;
    const MMTENPAY_CGICMD_WXCREDIT_VERIFY_PASSWD = 63;
    const MMTENPAY_CGICMD_WXCREDIT_AUTHEN = 64;
    const MMTENPAY_CGICMD_WXCREDIT_VERIFY = 65;
    const MMTENPAY_CGICMD_WXCREDIT_SIMPLE_VERIFY = 66;
    const MMTENPAY_CGICMD_WXCREDIT_QUERY_BILL_DETAIL = 67;
    const MMTENPAY_CGICMD_WXCREDIT_QUERY_PRIVILEGE = 68;
    const MMTENPAY_CGICMD_WXCREDIT_RENEW_IDENTIFY = 69;
    const MMTENPAY_BIZ_CGICMD_WX_QRY_AUTH_INFO = 70;
    const MMTENPAY_CGICMD_PAYUNREG = 71;
    const MMTENPAY_CGICMD_BIND_QUERY_NEW = 72;
    const MMTENPAY_CGICMD_ELEM_QUERY_NEW = 73;
    const MMTENPAY_CGICMD_GEN_PRE_SAVE = 74;
    const MMTENPAY_CGICMD_GEN_PRE_FETCH = 75;
    const MMTENPAY_CGICMD_VERIFY_BIND = 76;
    const MMTENPAY_CGICMD_USER_ROLL_SAVE_AND_FETCH = 77;
    const MMTENPAY_CGICMD_QRCODE_TO_BARCODE = 78;
    const MMTENPAY_CGICMD_CHKPAYACC = 79;
    const MMTENPAY_CGICMD_QUERY_REFUND = 80;
    const MMTENPAY_CGICMD_WX_HBAA_TRANSFER = 81;
    const MMTENPAY_CGICMD_WX_PAY_CONFIRM = 82;
    const MMTENPAY_CGICMD_GEN_PRE_TRANSFER = 83;
    const MMTENPAY_CGICMD_QUERY_TRANSFER_STATUS = 84;
    const MMTENPAY_CGICMD_TRANSFER_CONFIRM = 85;
    const MMTENPAY_CGICMD_TRANSFER_RETRYSENDMESSAGE = 86;
    const MMTENPAY_CGICMD_PAYRELAY = 87;
    const MMTENPAY_CGICMD_WX_GET_MERSIGN_ORDER = 88;
    const MMTENPAY_CGICMD_WX_VERIFY_MERSIGN = 89;
    const MMTENPAY_CGICMD_WX_GET_MERSIGN_SIMPLE = 90;
    const MMTENPAY_CGICMD_WX_QUERY_SP_BANK = 91;
    const MMTENPAY_CGICMD_NONPAY = 92;
    const MMTENPAY_CGICMD_WX_QUERY_BANK_ROLL_LIST_BATCH = 93;
    const MMTENPAY_CGICMD_GET_FIXED_AMOUNT_QRCODE = 94;
    const MMTENPAY_CGICMD_TRANSFER_GET_USERNAME = 95;
    const MMTENPAY_CGICMD_WX_QUERY_ORDER = 96;
    const MMTENPAY_CGICMD_TRANSFEAR_SEND_CANCEL_MSG = 97;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MMTENPAY_CGICMD_AUTHEN' => self::MMTENPAY_CGICMD_AUTHEN,
            'MMTENPAY_CGICMD_VERIFY' => self::MMTENPAY_CGICMD_VERIFY,
            'MMTENPAY_CGICMD_USER_ROLL' => self::MMTENPAY_CGICMD_USER_ROLL,
            'MMTENPAY_CGICMD_USER_ROLL_BATCH' => self::MMTENPAY_CGICMD_USER_ROLL_BATCH,
            'MMTENPAY_CGICMD_QRCODE_CREATE' => self::MMTENPAY_CGICMD_QRCODE_CREATE,
            'MMTENPAY_CGICMD_QRCODE_USE' => self::MMTENPAY_CGICMD_QRCODE_USE,
            'MMTENPAY_CGICMD_BANK_QUERY' => self::MMTENPAY_CGICMD_BANK_QUERY,
            'MMTENPAY_CGICMD_CHANGE_PWD' => self::MMTENPAY_CGICMD_CHANGE_PWD,
            'MMTENPAY_CGICMD_RESET_PWD_AUTHEN' => self::MMTENPAY_CGICMD_RESET_PWD_AUTHEN,
            'MMTENPAY_CGICMD_RESET_PWD_VERIFY' => self::MMTENPAY_CGICMD_RESET_PWD_VERIFY,
            'MMTENPAY_CGICMD_BIND_AUTHEN' => self::MMTENPAY_CGICMD_BIND_AUTHEN,
            'MMTENPAY_CGICMD_BIND_VERIFY' => self::MMTENPAY_CGICMD_BIND_VERIFY,
            'MMTENPAY_CGICMD_UNBIND' => self::MMTENPAY_CGICMD_UNBIND,
            'MMTENPAY_CGICMD_BANKCARDBIN_QUERY' => self::MMTENPAY_CGICMD_BANKCARDBIN_QUERY,
            'MMTENPAY_CGICMD_VERIFY_REG' => self::MMTENPAY_CGICMD_VERIFY_REG,
            'MMTENPAY_CGICMD_BIND_VERIFY_REG' => self::MMTENPAY_CGICMD_BIND_VERIFY_REG,
            'MMTENPAY_CGICMD_CHECK_PWD' => self::MMTENPAY_CGICMD_CHECK_PWD,
            'MMTENPAY_CGICMD_TIMESEED' => self::MMTENPAY_CGICMD_TIMESEED,
            'MMTENPAY_CGICMD_RESET_PWD' => self::MMTENPAY_CGICMD_RESET_PWD,
            'MMTENPAY_CGICMD_PUBLIC_API' => self::MMTENPAY_CGICMD_PUBLIC_API,
            'MMTENPAY_BIZ_CGICMD_WEB_QUERY_CHECK_RECORD' => self::MMTENPAY_BIZ_CGICMD_WEB_QUERY_CHECK_RECORD,
            'MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_CHECK_RECORD' => self::MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_CHECK_RECORD,
            'MMTENPAY_BIZ_CGICMD_WEB_QUERY_CHECK_RESULT' => self::MMTENPAY_BIZ_CGICMD_WEB_QUERY_CHECK_RESULT,
            'MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_CHECK_RESULT' => self::MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_CHECK_RESULT,
            'MMTENPAY_BIZ_CGICMD_WEB_NOTIFY_CHECK_RESULT' => self::MMTENPAY_BIZ_CGICMD_WEB_NOTIFY_CHECK_RESULT,
            'MMTENPAY_BIZ_CGICMD_PLATFORM_NOTIFY_CHECK_RESULT' => self::MMTENPAY_BIZ_CGICMD_PLATFORM_NOTIFY_CHECK_RESULT,
            'MMTENPAY_CGICMD_MCH_TRADE' => self::MMTENPAY_CGICMD_MCH_TRADE,
            'MMTENPAY_GW_CGICMD_NORMAL_ORDER_QUERY' => self::MMTENPAY_GW_CGICMD_NORMAL_ORDER_QUERY,
            'MMTENPAY_CGICMD_QUERY_USER_TYPE' => self::MMTENPAY_CGICMD_QUERY_USER_TYPE,
            'MMTENPAY_GW_CGICMD_VERIFY_NOTIFY_ID' => self::MMTENPAY_GW_CGICMD_VERIFY_NOTIFY_ID,
            'MMTENPAY_GW_CGICMD_NORMAL_REFUND_QUERY' => self::MMTENPAY_GW_CGICMD_NORMAL_REFUND_QUERY,
            'MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_BZJ_INFO' => self::MMTENPAY_BIZ_CGICMD_PLATFORM_QUERY_BZJ_INFO,
            'MMTENPAY_CGICMD_WX_OFFLINE_AUTHEN' => self::MMTENPAY_CGICMD_WX_OFFLINE_AUTHEN,
            'MMTENPAY_CGICMD_WX_OFFLINE_PAY' => self::MMTENPAY_CGICMD_WX_OFFLINE_PAY,
            'MMTENPAY_CGICMD_IMPORT_BIND_QUERY' => self::MMTENPAY_CGICMD_IMPORT_BIND_QUERY,
            'MMTENPAY_CGICMD_IMPORT_ENCRYPT_QUERY' => self::MMTENPAY_CGICMD_IMPORT_ENCRYPT_QUERY,
            'MMTENPAY_CGICMD_WX_FUND_BUY' => self::MMTENPAY_CGICMD_WX_FUND_BUY,
            'MMTENPAY_CGICMD_WX_FUND_REDEM' => self::MMTENPAY_CGICMD_WX_FUND_REDEM,
            'MMTENPAY_CGICMD_WX_FUND_CHANGE' => self::MMTENPAY_CGICMD_WX_FUND_CHANGE,
            'MMTENPAY_CGICMD_WX_FUND_BINDSP_QUERY' => self::MMTENPAY_CGICMD_WX_FUND_BINDSP_QUERY,
            'MMTENPAY_CGICMD_WX_FUND_ACCOUNT_QUERY' => self::MMTENPAY_CGICMD_WX_FUND_ACCOUNT_QUERY,
            'MMTENPAY_CGICMD_WX_FUND_PROFIT_QUERY' => self::MMTENPAY_CGICMD_WX_FUND_PROFIT_QUERY,
            'MMTENPAY_CGICMD_WX_FUND_SUPPORT_BANK' => self::MMTENPAY_CGICMD_WX_FUND_SUPPORT_BANK,
            'MMTENPAY_CGICMD_OFFLINE_CREATE' => self::MMTENPAY_CGICMD_OFFLINE_CREATE,
            'MMTENPAY_CGICMD_OFFLINE_CLOSE' => self::MMTENPAY_CGICMD_OFFLINE_CLOSE,
            'MMTENPAY_CGICMD_OFFLINE_FPAY' => self::MMTENPAY_CGICMD_OFFLINE_FPAY,
            'MMTENPAY_CGICMD_OFFLINE_QUERY_USER' => self::MMTENPAY_CGICMD_OFFLINE_QUERY_USER,
            'MMTENPAY_CGICMD_OFFLINE_CHG_FEE' => self::MMTENPAY_CGICMD_OFFLINE_CHG_FEE,
            'MMTENPAY_CGICMD_OFFLINE_UNFREEZE' => self::MMTENPAY_CGICMD_OFFLINE_UNFREEZE,
            'MMTENPAY_CGICMD_OFFLINE_GET_TOKEN' => self::MMTENPAY_CGICMD_OFFLINE_GET_TOKEN,
            'MMTENPAY_CGICMD_WX_HB_REDPACKETNOTIFY' => self::MMTENPAY_CGICMD_WX_HB_REDPACKETNOTIFY,
            'MMTENPAY_CGICMD_WX_SP_CLOSE_ORDER' => self::MMTENPAY_CGICMD_WX_SP_CLOSE_ORDER,
            'MMTENPAY_BIZ_CGICMD_QUERY_NEW_PARTNER_ID' => self::MMTENPAY_BIZ_CGICMD_QUERY_NEW_PARTNER_ID,
            'MMTENPAY_BIZ_CGICMD_QUERY_BIZ_CHECK_RESULT' => self::MMTENPAY_BIZ_CGICMD_QUERY_BIZ_CHECK_RESULT,
            'MMTENPAY_CGICMD_WXCREDIT_QUERY' => self::MMTENPAY_CGICMD_WXCREDIT_QUERY,
            'MMTENPAY_CGICMD_WXCREDIT_QUERY_CARD_DETAIL' => self::MMTENPAY_CGICMD_WXCREDIT_QUERY_CARD_DETAIL,
            'MMTENPAY_CGICMD_WXCREDIT_QUERY_QUESTION' => self::MMTENPAY_CGICMD_WXCREDIT_QUERY_QUESTION,
            'MMTENPAY_CGICMD_WXCREDIT_COMMIT_QUESTION' => self::MMTENPAY_CGICMD_WXCREDIT_COMMIT_QUESTION,
            'MMTENPAY_CGICMD_WXCREDIT_REPAY' => self::MMTENPAY_CGICMD_WXCREDIT_REPAY,
            'MMTENPAY_CGICMD_WXCREDIT_UNBIND' => self::MMTENPAY_CGICMD_WXCREDIT_UNBIND,
            'MMTENPAY_CGICMD_WXCREDIT_VERIFY_PASSWD' => self::MMTENPAY_CGICMD_WXCREDIT_VERIFY_PASSWD,
            'MMTENPAY_CGICMD_WXCREDIT_AUTHEN' => self::MMTENPAY_CGICMD_WXCREDIT_AUTHEN,
            'MMTENPAY_CGICMD_WXCREDIT_VERIFY' => self::MMTENPAY_CGICMD_WXCREDIT_VERIFY,
            'MMTENPAY_CGICMD_WXCREDIT_SIMPLE_VERIFY' => self::MMTENPAY_CGICMD_WXCREDIT_SIMPLE_VERIFY,
            'MMTENPAY_CGICMD_WXCREDIT_QUERY_BILL_DETAIL' => self::MMTENPAY_CGICMD_WXCREDIT_QUERY_BILL_DETAIL,
            'MMTENPAY_CGICMD_WXCREDIT_QUERY_PRIVILEGE' => self::MMTENPAY_CGICMD_WXCREDIT_QUERY_PRIVILEGE,
            'MMTENPAY_CGICMD_WXCREDIT_RENEW_IDENTIFY' => self::MMTENPAY_CGICMD_WXCREDIT_RENEW_IDENTIFY,
            'MMTENPAY_BIZ_CGICMD_WX_QRY_AUTH_INFO' => self::MMTENPAY_BIZ_CGICMD_WX_QRY_AUTH_INFO,
            'MMTENPAY_CGICMD_PAYUNREG' => self::MMTENPAY_CGICMD_PAYUNREG,
            'MMTENPAY_CGICMD_BIND_QUERY_NEW' => self::MMTENPAY_CGICMD_BIND_QUERY_NEW,
            'MMTENPAY_CGICMD_ELEM_QUERY_NEW' => self::MMTENPAY_CGICMD_ELEM_QUERY_NEW,
            'MMTENPAY_CGICMD_GEN_PRE_SAVE' => self::MMTENPAY_CGICMD_GEN_PRE_SAVE,
            'MMTENPAY_CGICMD_GEN_PRE_FETCH' => self::MMTENPAY_CGICMD_GEN_PRE_FETCH,
            'MMTENPAY_CGICMD_VERIFY_BIND' => self::MMTENPAY_CGICMD_VERIFY_BIND,
            'MMTENPAY_CGICMD_USER_ROLL_SAVE_AND_FETCH' => self::MMTENPAY_CGICMD_USER_ROLL_SAVE_AND_FETCH,
            'MMTENPAY_CGICMD_QRCODE_TO_BARCODE' => self::MMTENPAY_CGICMD_QRCODE_TO_BARCODE,
            'MMTENPAY_CGICMD_CHKPAYACC' => self::MMTENPAY_CGICMD_CHKPAYACC,
            'MMTENPAY_CGICMD_QUERY_REFUND' => self::MMTENPAY_CGICMD_QUERY_REFUND,
            'MMTENPAY_CGICMD_WX_HBAA_TRANSFER' => self::MMTENPAY_CGICMD_WX_HBAA_TRANSFER,
            'MMTENPAY_CGICMD_WX_PAY_CONFIRM' => self::MMTENPAY_CGICMD_WX_PAY_CONFIRM,
            'MMTENPAY_CGICMD_GEN_PRE_TRANSFER' => self::MMTENPAY_CGICMD_GEN_PRE_TRANSFER,
            'MMTENPAY_CGICMD_QUERY_TRANSFER_STATUS' => self::MMTENPAY_CGICMD_QUERY_TRANSFER_STATUS,
            'MMTENPAY_CGICMD_TRANSFER_CONFIRM' => self::MMTENPAY_CGICMD_TRANSFER_CONFIRM,
            'MMTENPAY_CGICMD_TRANSFER_RETRYSENDMESSAGE' => self::MMTENPAY_CGICMD_TRANSFER_RETRYSENDMESSAGE,
            'MMTENPAY_CGICMD_PAYRELAY' => self::MMTENPAY_CGICMD_PAYRELAY,
            'MMTENPAY_CGICMD_WX_GET_MERSIGN_ORDER' => self::MMTENPAY_CGICMD_WX_GET_MERSIGN_ORDER,
            'MMTENPAY_CGICMD_WX_VERIFY_MERSIGN' => self::MMTENPAY_CGICMD_WX_VERIFY_MERSIGN,
            'MMTENPAY_CGICMD_WX_GET_MERSIGN_SIMPLE' => self::MMTENPAY_CGICMD_WX_GET_MERSIGN_SIMPLE,
            'MMTENPAY_CGICMD_WX_QUERY_SP_BANK' => self::MMTENPAY_CGICMD_WX_QUERY_SP_BANK,
            'MMTENPAY_CGICMD_NONPAY' => self::MMTENPAY_CGICMD_NONPAY,
            'MMTENPAY_CGICMD_WX_QUERY_BANK_ROLL_LIST_BATCH' => self::MMTENPAY_CGICMD_WX_QUERY_BANK_ROLL_LIST_BATCH,
            'MMTENPAY_CGICMD_GET_FIXED_AMOUNT_QRCODE' => self::MMTENPAY_CGICMD_GET_FIXED_AMOUNT_QRCODE,
            'MMTENPAY_CGICMD_TRANSFER_GET_USERNAME' => self::MMTENPAY_CGICMD_TRANSFER_GET_USERNAME,
            'MMTENPAY_CGICMD_WX_QUERY_ORDER' => self::MMTENPAY_CGICMD_WX_QUERY_ORDER,
            'MMTENPAY_CGICMD_TRANSFEAR_SEND_CANCEL_MSG' => self::MMTENPAY_CGICMD_TRANSFEAR_SEND_CANCEL_MSG,
        );
    }
}
}